name: Docker Image Build and Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build and Push Docker Image
      run: |
       echo "Ritu@18012003" | docker login -u "riturajput18" --password-stdin
       docker build -t ritu-pixel/fastapi-server:latest .
        docker push ritu-pixel/fastapi-server:latest
